# Generated by Django 4.2.7 on 2023-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookapp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('Liner', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Link', models.CharField(max_length=255)),
            ],
        ),
    ]
